export interface DisabledPaperConfig {
    examBoard: string | null;
    examLevel: string | null;
    subject: string | null;
    paper: string | null;
    series: string | null;
    year: number | null;
}

export const disabledPapersList: DisabledPaperConfig[] = [
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2011, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2012, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2013, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2014, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2015, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Jun", year: 2015, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2016, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2017, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2018, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2019, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Jun", year: 2020, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Jun", year: 2021, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "Chinese", series: "Nov", year: 2022, paper: null },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Physics', paper: null, series: 'Jun', year: 2020 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Chemistry', paper: null, series: 'Jun', year: 2020 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Biology', paper: null, series: 'Jun', year: 2020 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Mathematics', paper: null, series: 'Jun', year: 2020 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Physics', paper: null, series: 'Jan', year: 2019 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Chemistry', paper: null, series: 'Jan', year: 2019 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Biology', paper: null, series: 'Jan', year: 2019 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Mathematics', paper: null, series: 'Jan', year: 2019 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Physics', paper: null, series: 'Oct', year: 2018 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Chemistry', paper: null, series: 'Oct', year: 2018 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Biology', paper: null, series: 'Oct', year: 2018 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Mathematics', paper: null, series: 'Oct', year: 2018 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Physics', paper: null, series: 'Oct', year: 2015 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Chemistry', paper: null, series: 'Oct', year: 2015 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Biology', paper: null, series: 'Oct', year: 2015 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Mathematics', paper: null, series: 'Oct', year: 2015 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Physics', paper: null, series: 'Jun', year: 2014 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Chemistry', paper: null, series: 'Jun', year: 2014 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Biology', paper: null, series: 'Jun', year: 2014 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Mathematics', paper: null, series: 'Jun', year: 2014 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Physics', paper: null, series: 'Oct', year: 2014 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Chemistry', paper: null, series: 'Oct', year: 2014 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Biology', paper: null, series: 'Oct', year: 2014 },
    { examBoard: 'Edexcel', examLevel: 'IAL', subject: 'Mathematics', paper: null, series: 'Oct', year: 2014 },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Nov", year: 2022, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Jan", year: 2021, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Jun", year: 2020, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Nov", year: 2019, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Nov", year: 2018, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Nov", year: 2017, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Nov", year: 2016, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Nov", year: 2015, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Nov", year: 2014, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Nov", year: 2013, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English A", series: "Nov", year: 2012, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Nov", year: 2022, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Jan", year: 2021, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Jun", year: 2020, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Nov", year: 2019, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Nov", year: 2018, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Nov", year: 2017, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Nov", year: 2016, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Nov", year: 2015, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Nov", year: 2014, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Nov", year: 2013, paper: null },
    { examBoard: "Edexcel", examLevel: "IGCSE", subject: "English B", series: "Nov", year: 2012, paper: null },
];
